### ISSUE TITLE
string that are alphanumeric and that have at least one occurrence of 2 or more digit integer in it 

### ISSUE THREAD

**Issue by srjkrl20011991** [ziishaned/learn-regex#127]
need regex expression urgently for above topic

**Comment by Chuddington** [comment]
(?:\w+)?(?:\d{2})(?:\w+)? Would match to strings 0 or more letters, with two digits in the middle, with 0 or more letters after.  This regex doesn't capture anything to use later, as denoted by the (?: prefixes

Maybe have a look at the regex 101 website and have a play around with the regex to see if you can increase the limit

**Comment by Clearlove9** [comment]
邮件已收到，谢谢！
