### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by mrtheyann** [ziishaned/learn-regex#142]
- Hello, I've found this repository very useful for begginers, so I decide to translate it to Russian.
I've seen a similar issue from 2017 but it looks like this translation is kinda abandoned now.

- I made a fork of this repo so I could merge it later when job would be done.
Readme file for translators asks to create an issue for a collaboration with other translators, however, it seems like there is not too much of work in here to do, so I am able to translate this all alone. 

- I'll be right back in here when job would be done, cheers.

**Comment by mrtheyann** [comment]
- I also wonder if it is okay to add a few extra links for Russian speakers somewhere below the contents part so people would have an external link to go deeper through regexps. 

- I guess they're kinda useless for other languages' speakers because they're directly Russian.
Example: https://learn.javascript.ru/regular-expressions-javascript

**Comment by mrtheyann** [comment]
Translation is done.

The pull request following:
https://github.com/ziishaned/learn-regex/pull/143

**Comment by ziishaned** [comment]
Thanks 👍
