### ISSUE TITLE
Confustion about [] and (|)

### ISSUE THREAD

**Issue by hacker0limbo** [ziishaned/learn-regex#168]
Hey: 

Really enjoyed learning with your fantastic tutorial, however, as a beginner i personally still got one confusion:

I can do this:
```javascript
"[Tt]he" => The car parked in the garage.
```

or either do this:
```javascript
"(T|t)he" => The car parked in the garage.
```
which, both match `The` and `the`, so is there any difference? 

Forgive me with my poor English, Cheers!

**Comment by ziishaned** [comment]
`[]` is used to capture a single character. For example:

![image](https://user-images.githubusercontent.com/16267321/64957042-08c36900-d89d-11e9-9463-49d3505a43a1.png)

`()` is used to capture a group of character in a specific sequence: For example:

![image](https://user-images.githubusercontent.com/16267321/64957061-137dfe00-d89d-11e9-861d-fad175092ee2.png)
